#!/bin/bash
PATCHFILE=squeezecenter_squeezeslave_player3-7.4.patch
svn diff -r42 Slim/Player/SqueezeSlave.pm > ${PATCHFILE}
svn diff -r42 Slim/Networking/Slimproto.pm >> ${PATCHFILE}
svn diff -r42 Slim/Display/Text.pm >> ${PATCHFILE}
svn diff -r42 Slim/Display/Lib/TextVFD.pm >> ${PATCHFILE}
cp -ip ${PATCHFILE} ../squeezeslave/patches
